spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          time_zone: Asia/Kolkata

  h2:
    console:
      enabled: true

  flyway:
    enabled: false

  security:
    oauth2:
      client:
        registration: { }
        provider: { }
    jwt:
      secret-key: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
      expiration: 86400000

application:
  frontend:
    url: "http://test-frontend.com"
